[project]
name = "fiap-tech-challenge-sub-fase-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115",
    "ipykernel>=7.3.0",
    "joblib>=1.5.3",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "mlflow>=3",
    "openpyxl>=3.1.5",
    "pandas<3",
    "requests>=2.32",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "streamlit>=1.61.1",
    "uvicorn[standard]>=0.32",
    "xgboost>=3.2.0",
]
